#!/bin/bash

# Add changes and commit with user-provided message
git add .
echo 'Commit message:'
read commitMessage
git commit -m "$commitMessage"

# Push changes to GitHub with user-provided branch and credentials
echo 'Enter the name of the branch:'
read branch
git push --set-upstream origin $branch -u $username:$password

# Wait for user input before exiting
read

